





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Fields;
using Sitecore.Data;
using Sitecore.ContentSearch;
using Glass.Mapper.Sc.Configuration;


namespace Feature.EndUserSession.DataTransferObjects
{

/// <summary>
	/// IEndUserSessionObject Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Features/EndUserSession/EndUserSession</para>	
	/// <para>ID: 6005714a-e69e-4977-8e81-8942635f23f8</para>	
	/// </summary>
	[SitecoreType(TemplateId=EndUserSessionConstants.TemplateIdString )] //, Cachable = true
	public partial interface IEndUserSessionObject : IModelBase 
	{
								/// <summary>
					/// The EndUserSessionImage field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 81c0bf6d-8416-4e99-bc04-58fd59c0a500</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(EndUserSessionConstants.EndUserSessionImageFieldName)]
					Image EndUserSessionImage  {get; set;}
			
								/// <summary>
					/// The EndUserSessionMessage field.
					/// <para>Message to display to the user</para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: de00a996-42e9-49dc-809a-96d56841baeb</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(EndUserSessionConstants.EndUserSessionMessageFieldName)]
					string EndUserSessionMessage  {get; set;}
			
								/// <summary>
					/// The EndUserSessionTitle field.
					/// <para>title displayed as h2-tag</para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: efeff65a-16ba-47e3-891c-0f6d493e0f81</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(EndUserSessionConstants.EndUserSessionTitleFieldName)]
					string EndUserSessionTitle  {get; set;}
			
								/// <summary>
					/// The EndUserSessionUrl field.
					/// <para>URL user's can click to take a next action. Link Description will be shown for text.</para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 55a80586-47be-4f64-a619-72747d1f8e71</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(EndUserSessionConstants.EndUserSessionUrlFieldName)]
					Link EndUserSessionUrl  {get; set;}
			
				}


public static partial class EndUserSessionConstants{

		public const string TemplateIdString = "6005714a-e69e-4977-8e81-8942635f23f8";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "EndUserSession";

				
		public static readonly ID EndUserSessionImageFieldId = new ID("81c0bf6d-8416-4e99-bc04-58fd59c0a500");
		public const string EndUserSessionImageFieldName = "EndUserSessionImage";
			
				
		public static readonly ID EndUserSessionMessageFieldId = new ID("de00a996-42e9-49dc-809a-96d56841baeb");
		public const string EndUserSessionMessageFieldName = "EndUserSessionMessage";
			
				
		public static readonly ID EndUserSessionTitleFieldId = new ID("efeff65a-16ba-47e3-891c-0f6d493e0f81");
		public const string EndUserSessionTitleFieldName = "EndUserSessionTitle";
			
				
		public static readonly ID EndUserSessionUrlFieldId = new ID("55a80586-47be-4f64-a619-72747d1f8e71");
		public const string EndUserSessionUrlFieldName = "EndUserSessionUrl";
			
		

}

	
	/// <summary>
	/// EndUserSessionObject
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Features/EndUserSession/EndUserSession</para>	
	/// <para>ID: 6005714a-e69e-4977-8e81-8942635f23f8</para>	
	/// </summary>
	[SitecoreType(TemplateId=EndUserSessionConstants.TemplateIdString, AutoMap = true)] //, Cachable = true	
	public partial class EndUserSessionObject  : ModelBase, IEndUserSessionObject
	{

						/// <summary>
				/// The EndUserSessionImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 81c0bf6d-8416-4e99-bc04-58fd59c0a500</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(EndUserSessionConstants.EndUserSessionImageFieldName), IndexField("EndUserSessionImage")]							
				public virtual Image EndUserSessionImage  {get; set;}		
				
							
						/// <summary>
				/// The EndUserSessionMessage field.
				/// <para>Message to display to the user</para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: de00a996-42e9-49dc-809a-96d56841baeb</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(EndUserSessionConstants.EndUserSessionMessageFieldName, Setting = SitecoreFieldSettings.RichTextRaw), IndexField("EndUserSessionMessage")]							
				public virtual string EndUserSessionMessage  {get; set;}		
				
							
						/// <summary>
				/// The EndUserSessionTitle field.
				/// <para>title displayed as h2-tag</para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: efeff65a-16ba-47e3-891c-0f6d493e0f81</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(EndUserSessionConstants.EndUserSessionTitleFieldName), IndexField("EndUserSessionTitle")]							
				public virtual string EndUserSessionTitle  {get; set;}		
				
							
						/// <summary>
				/// The EndUserSessionUrl field.
				/// <para>URL user's can click to take a next action. Link Description will be shown for text.</para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 55a80586-47be-4f64-a619-72747d1f8e71</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(EndUserSessionConstants.EndUserSessionUrlFieldName), IndexField("EndUserSessionUrl")]							
				public virtual Link EndUserSessionUrl  {get; set;}		
				
							
			
	}
}
